CREATE DATABASE IF NOT EXISTS farmed;

CREATE DATABASE IF NOT EXISTS farmed;CREATE TABLE IF NOT EXISTS user_details(id INTEGER PRIMARY KEY AUTO_INCREMENT,user_name VARCHAR(50),email VARCHAR(50) UNIQUE,user_password  VARCHAR(100),date_joined VARCHAR(50));



CREATE TABLE IF NOT EXISTS posts(id INTEGER PRIMARY KEY AUTO_INCREMENT,title VARCHAR(50),post VARCHAR(500),date_posted VARCHAR(50),user_id INTEGER, FOREIGN KEY(user_id) REFERENCES users_details(id));


CREATE TABLE feedbacks(id INTEGER PRIMARY KEY AUTO_INCREMENT,feedback_title(200),feedback VARCHAR(300), time_posted VARCHAR(30),user_id INTEGER, FOREIGN KEY(user_id) REFERENCES user_details(id));


CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTO_INCREMENT,user_id INTEGER, FOREIGN KEY(user_id) REFERENCES user_details(id));
